# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test execution
      run: mvn test
    - name: OWASP ZAP Baseline Scan
      # You may pin to the exact commit or the version.
      # uses: zaproxy/action-baseline@3f53f375845c0b410cb54dde95f77516fc4fcf4c
      uses: zaproxy/action-baseline@v0.3.0
